server:
  port: 8010
spring:
  application:
    name: discovery-service
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    prefer-ip-address: true
